document.addEventListener('DOMContentLoaded', () => {
    // Modo oscuro
    const toggleButton = document.getElementById('toggleDarkMode');
    const currentMode = localStorage.getItem('mode') || 'light';

    applyMode(currentMode);

    toggleButton.addEventListener('click', () => {
        const newMode = document.body.classList.contains('light-mode') ? 'dark' : 'light';
        applyMode(newMode);
        localStorage.setItem('mode', newMode);
    });

    function applyMode(mode) {
        document.body.classList.remove('light-mode', 'dark-mode');
        toggleButton.classList.remove('light-mode', 'dark-mode');
        
        document.body.classList.add(`${mode}-mode`);
        toggleButton.classList.add(`${mode}-mode`);
        
        document.querySelectorAll('.darklight, .colors, .tows, .towse, .towsi, .towsis, .borde').forEach(element => {
            element.classList.remove('light-mode', 'dark-mode');
            element.classList.add(`${mode}-mode`);
        });
    }

    // Traducción
    const texts = {
        es: {
            title: "Bienvenido, comienza ahora",
            description: "Crea tu cuenta y no te pierdas de nada",
            content: "Recuerda tu nombre de usuario y contraseña para acceder a tu cuenta.",
            register: "Registrarse",
            login: "Iniciar sesión",
            alreadyHaveAccount: "¿Ya tienes una cuenta?",
            search: "Buscar",
            username: "Nombre de usuario",
            name: "Nombre",
            password: "Contraseña",
            aboutYou: "Sobre ti",
            link: "Enlace",
            home: "Inicio",
            notifications: "Notificaciones",
            upload: "Subir",
            profile: "Perfil",
            logout: "Cerrar sesión",
            stats: "Estadísticas",
            feed: "Feed",
            video: "Video",
            image: "Imagen",
            posts: "Publicaciones",
            following: "Siguiendo",
            followers: "Seguidores",
            editInfo: "Editar información",
            editProfile: "Editar perfil",
            edit: "Editar",
            explore: "Explorar",
            popular: "Popular",
            follow: "Seguir",
            block: "Bloquear",
            blocked: "Bloqueado",
            views: "Vistas",
            likes: "Me gusta",
            post: "Publicar",
            liked: "Me gusta",
            no: "No recuerdo mi contraseña",
            banner: "Banner",
            share: "Compartir",
            options: "Opciones",
            delete: "Borrar",
            report: "Denunciar",
            page: "Página",
            comment: "Comentar",
            messages: "Mensajes",
            save: "Guardar",
            friends: "Amigos",
            groups: "Grupos",
            settings: "Ajustes"
        },
        lk: {
            title: "Biande ondent oup",
            description: "Kopetery oup ondent er secciuser ed no ert daska in nade",
            content: "Ruk er nammer in user ed secretauser forrar acced ior secciuser.",
            register: "Redur",
            login: "ondent seccione",
            alreadyHaveAccount: "Ert Fuher secciuser",
            search: "Fety",
            username: "User",
            name: "nammer",
            password: "Secretauser",
            aboutYou: "Ino in ar",
            link: "Enlink",
            home: "Deos",
            notifications: "Notiffins",
            upload: "Upt",
            profile: "Personal",
            logout: "Nainder sesin",
            stats: "Gewer",
            feed: "Feed",
            video: "Video",
            image: "Imart",
            posts: "Upter",
            following: "Drika",
            followers: "Drikis",
            editInfo: "Editare inframe",
            editProfile: "Editare personal",
            edit: "Editare",
            explore: "Naver",
            popular: "Favere",
            follow: "Drik",
            following: "Drika",
            block: "Flagster",
            blocked: "Flagsder",
            views: "Aquer",
            likes: "Uop amaler",
            post: "Upter",
            liked: "Oup amaler",
            no: "nainnen fool",
            banner: "Banner"
        },
        en: {
            title: "Welcome, start now",
            description: "Create your account and don't miss anything",
            content: "Remember your username and password to access your account.",
            register: "Sign up",
            login: "Log in",
            alreadyHaveAccount: "Already have an account?",
            search: "Search",
            username: "Username",
            name: "Name",
            password: "Password",
            aboutYou: "About you",
            link: "Link",
            home: "Home",
            notifications: "Notifications",
            upload: "Upload",
            profile: "Profile",
            logout: "Log out",
            stats: "Statistics",
            feed: "Feed",
            video: "Video",
            image: "Image",
            posts: "Posts",
            following: "Following",
            followers: "Followers",
            editInfo: "Edit info",
            editProfile: "Edit profile",
            edit: "Edit",
            explore: "Explore",
            popular: "Popular",
            follow: "Follow",
            block: "Block",
            blocked: "Blocked",
            views: "Views",
            likes: "Likes",
            post: "Post",
            liked: "Liked",
            no: "I don't remember my password",
            banner: "Banner",
            share: "Share",
            options: "Options",
            delete: "Delete",
            report: "Report",
            page: "Page",
            comment: "Comment",
            messages: "Messages",
            save: "Save",
            friends: "Friends",
            groups: "Groups",
            settings: "Settings"
        },
    
        // Agrega las traducciones de japonés, alemán, ruso, portugués y francés aquí...
        ja: {
            title: "ようこそ、今すぐ始めましょう",
            description: "アカウントを作成して、すべてを見逃さないようにしましょう",
            content: "アカウントにアクセスするためのユーザー名とパスワードを覚えてください。",
            register: "登録",
            login: "ログイン",
            alreadyHaveAccount: "すでにアカウントをお持ちですか？",
            search: "検索",
            username: "ユーザー名",
            name: "名前",
            password: "パスワード",
            aboutYou: "あなたについて",
            link: "リンク",
            home: "ホーム",
            notifications: "通知",
            upload: "アップロード",
            profile: "プロフィール",
            logout: "ログアウト",
            stats: "統計",
            feed: "フィード",
            video: "ビデオ",
            image: "画像",
            posts: "投稿",
            following: "フォロー中",
            followers: "フォロワー",
            editInfo: "情報を編集",
            editProfile: "プロフィールを編集",
            edit: "編集",
            explore: "探検する",
            popular: "人気",
            follow: "フォロー",
            block: "ブロック",
            blocked: "ブロック済み",
            views: "ビュー",
            likes: "いいね",
            post: "投稿",
            liked: "いいね済み",
            no: "パスワードを思い出せません",
            banner: "バナー",
            share: "共有する",
            options: "オプション",
            delete: "削除",
            report: "報告",
            page: "ページ",
            comment: "コメント",
            messages: "メッセージ",
            save: "保存",
            friends: "友達",
            groups: "グループ",
            settings: "設定"
        },
        de: {
            title: "Willkommen, jetzt starten",
            description: "Erstellen Sie ein Konto und verpassen Sie nichts",
            content: "Merken Sie sich Ihren Benutzernamen und Ihr Passwort, um auf Ihr Konto zuzugreifen.",
            register: "Registrieren",
            login: "Anmelden",
            alreadyHaveAccount: "Haben Sie bereits ein Konto?",
            search: "Suchen",
            username: "Benutzername",
            name: "Name",
            password: "Passwort",
            aboutYou: "Über dich",
            link: "Link",
            home: "Startseite",
            notifications: "Benachrichtigungen",
            upload: "Hochladen",
            profile: "Profil",
            logout: "Abmelden",
            stats: "Statistiken",
            feed: "Feed",
            video: "Video",
            image: "Bild",
            posts: "Beiträge",
            following: "Folgen",
            followers: "Follower",
            editInfo: "Informationen bearbeiten",
            editProfile: "Profil bearbeiten",
            edit: "Bearbeiten",
            explore: "Entdecken",
            popular: "Beliebt",
            follow: "Folgen",
            block: "Blockieren",
            blocked: "Blockiert",
            views: "Ansichten",
            likes: "Gefällt mir",
            post: "Posten",
            liked: "Gefallen",
            no: "Passwort vergessen",
            banner: "Banner",
            share: "Teilen",
            options: "Optionen",
            delete: "Löschen",
            report: "Melden",
            page: "Seite",
            comment: "Kommentieren",
            messages: "Nachrichten",
            save: "Speichern",
            friends: "Freunde",
            groups: "Gruppen",
            settings: "Einstellungen"
        },
        ru: {
            title: "Добро пожаловать, начните сейчас",
            description: "Создайте учетную запись и не пропустите ничего",
            content: "Запомните ваше имя пользователя и пароль для входа в аккаунт.",
            register: "Регистрация",
            login: "Войти",
            alreadyHaveAccount: "Уже есть аккаунт?",
            search: "Поиск",
            username: "Имя пользователя",
            name: "Имя",
            password: "Пароль",
            aboutYou: "О вас",
            link: "Ссылка",
            home: "Главная",
            notifications: "Уведомления",
            upload: "Загрузить",
            profile: "Профиль",
            logout: "Выйти",
            stats: "Статистика",
            feed: "Лента",
            video: "Видео",
            image: "Изображение",
            posts: "Публикации",
            following: "Подписки",
            followers: "Подписчики",
            editInfo: "Редактировать информацию",
            editProfile: "Редактировать профиль",
            edit: "Редактировать",
            explore: "Исследовать",
            popular: "Популярное",
            follow: "Подписаться",
            block: "Заблокировать",
            blocked: "Заблокирован",
            views: "Просмотры",
            likes: "Нравится",
            post: "Опубликовать",
            liked: "Понравилось",
            no: "Не помню пароль",
            banner: "Баннер",
            share: "Поделиться",
            options: "Опции",
            delete: "Удалить",
            report: "Пожаловаться",
            page: "Страница",
            comment: "Комментировать",
            messages: "Сообщения",
            save: "Сохранить",
            friends: "Друзья",
            groups: "Группы",
            settings: "Настройки"
        },
        pt: {
            title: "Bem-vindo, comece agora",
            description: "Crie sua conta e não perca nada",
            content: "Lembre-se do seu nome de usuário e senha para acessar sua conta.",
            register: "Cadastre-se",
            login: "Entrar",
            alreadyHaveAccount: "Já tem uma conta?",
            search: "Pesquisar",
            username: "Nome de usuário",
            name: "Nome",
            password: "Senha",
            aboutYou: "Sobre você",
            link: "Link",
            home: "Início",
            notifications: "Notificações",
            upload: "Enviar",
            profile: "Perfil",
            logout: "Sair",
            stats: "Estatísticas",
            feed: "Feed",
            video: "Vídeo",
            image: "Imagem",
            posts: "Publicações",
            following: "Seguindo",
            followers: "Seguidores",
            editInfo: "Editar informações",
            editProfile: "Editar perfil",
            edit: "Editar",
            explore: "Explorar",
            popular: "Popular",
            follow: "Seguir",
            block: "Bloquear",
            blocked: "Bloqueado",
            views: "Visualizações",
            likes: "Curtidas",
            post: "Postar",
            liked: "Curtido",
            no: "Não me lembro da senha",
            banner: "Banner",
            share: "Compartilhar",
            options: "Opções",
            delete: "Excluir",
            report: "Denunciar",
            page: "Página",
            comment: "Comentar",
            messages: "Mensagens",
            save: "Salvar",
            friends: "Amigos",
            groups: "Grupos",
            settings: "Configurações"
        },
        fr: {
            title: "Bienvenue, commencez maintenant",
            description: "Créez votre compte et ne manquez rien",
            content: "Souvenez-vous de votre nom d'utilisateur et de votre mot de passe pour accéder à votre compte.",
            register: "S'inscrire",
            login: "Se connecter",
            alreadyHaveAccount: "Vous avez déjà un compte ?",
            search: "Rechercher",
            username: "Nom d'utilisateur",
            name: "Nom",
            password: "Mot de passe",
            aboutYou: "À propos de vous",
            link: "Lien",
            home: "Accueil",
            notifications: "Notifications",
            upload: "Télécharger",
            profile: "Profil",
            logout: "Se déconnecter",
            stats: "Statistiques",
            feed: "Fil d'actualité",
            video: "Vidéo",
            image: "Image",
            posts: "Publications",
            following: "Abonnements",
            followers: "Abonnés",
            editInfo: "Modifier les informations",
            editProfile: "Modifier le profil",
            edit: "Éditer",
            explore: "Explorer",
            popular: "Populaire",
            follow: "Suivre",
            block: "Bloquer",
            blocked: "Bloqué",
            views: "Vues",
            likes: "J'aime",
            post: "Publier",
            liked: "Aimé",
            no: "Mot de passe oublié",
            banner: "Bannière",
            share: "Partager",
            options: "Options",
            delete: "Supprimer",
            report: "Signaler",
            page: "Page",
            comment: "Commenter",
            messages: "Messages",
            save: "Sauvegarder",
            friends: "Amis",
            groups: "Groupes",
            settings: "Paramètres"
        },
        zh: {
            title: "欢迎，现在开始",
            description: "创建您的账户，不要错过任何信息",
            content: "记住您的用户名和密码，以便登录您的账户。",
            register: "注册",
            login: "登录",
            alreadyHaveAccount: "已经有账号？",
            search: "搜索",
            username: "用户名",
            name: "姓名",
            password: "密码",
            aboutYou: "关于你",
            link: "链接",
            home: "首页",
            notifications: "通知",
            upload: "上传",
            profile: "个人资料",
            logout: "登出",
            stats: "统计",
            feed: "动态",
            video: "视频",
            image: "图片",
            posts: "帖子",
            following: "关注",
            followers: "粉丝",
            editInfo: "编辑信息",
            editProfile: "编辑个人资料",
            edit: "编辑",
            explore: "探索",
            popular: "热门",
            follow: "关注",
            block: "屏蔽",
            blocked: "已屏蔽",
            views: "查看",
            likes: "点赞",
            post: "发布",
            liked: "已点赞",
            no: "忘记密码",
            banner: "横幅",
            share: "分享",
            options: "选项",
            delete: "删除",
            report: "举报",
            page: "页面",
            comment: "评论",
            messages: "消息",
            save: "保存",
            friends: "朋友",
            groups: "群组",
            settings: "设置"
        },
        hi: {
            title: "स्वागत है, अभी शुरू करें",
            description: "अपना खाता बनाएं और कुछ भी न चूकें",
            content: "अपने खाते तक पहुंचने के लिए अपना उपयोगकर्ता नाम और पासवर्ड याद रखें।",
            register: "रजिस्टर करें",
            login: "लॉग इन करें",
            alreadyHaveAccount: "क्या आपके पास पहले से खाता है?",
            search: "खोजें",
            username: "उपयोगकर्ता नाम",
            name: "नाम",
            password: "पासवर्ड",
            aboutYou: "आपके बारे में",
            link: "लिंक",
            home: "होम",
            notifications: "सूचनाएं",
            upload: "अपलोड करें",
            profile: "प्रोफ़ाइल",
            logout: "लॉग आउट करें",
            stats: "आँकड़े",
            feed: "फ़ीड",
            video: "वीडियो",
            image: "चित्र",
            posts: "पोस्ट",
            following: "अनुसरण",
            followers: "अनुयायी",
            editInfo: "जानकारी संपादित करें",
            editProfile: "प्रोफ़ाइल संपादित करें",
            edit: "संपादित करें",
            explore: "खोजें",
            popular: "लोकप्रिय",
            follow: "अनुसरण करें",
            block: "ब्लॉक करें",
            blocked: "ब्लॉक किया गया",
            views: "दृश्य",
            likes: "पसंद",
            post: "प्रकाशित करें",
            liked: "पसंद किया गया",
            no: "मुझे अपना पासवर्ड याद नहीं है",
            banner: "बैनर",
            share: "साझा करें",
            options: "विकल्प",
            delete: "हटाएं",
            report: "रिपोर्ट करें",
            page: "पृष्ठ",
            comment: "टिप्पणी करें",
            messages: "संदेश",
            save: "सहेजें",
            friends: "मित्र",
            groups: "समूह",
            settings: "सेटिंग्स"
        },
        ar: {
            title: "مرحبًا، ابدأ الآن",
            description: "أنشئ حسابك ولا تفوت أي شيء",
            content: "تذكر اسم المستخدم وكلمة المرور للوصول إلى حسابك.",
            register: "تسجيل",
            login: "تسجيل الدخول",
            alreadyHaveAccount: "هل لديك حساب بالفعل؟",
            search: "بحث",
            username: "اسم المستخدم",
            name: "الاسم",
            password: "كلمة المرور",
            aboutYou: "حولك",
            link: "رابط",
            home: "الصفحة الرئيسية",
            notifications: "الإشعارات",
            upload: "رفع",
            profile: "الملف الشخصي",
            logout: "تسجيل الخروج",
            stats: "الإحصائيات",
            feed: "الخلاصة",
            video: "فيديو",
            image: "صورة",
            posts: "المنشورات",
            following: "يتابع",
            followers: "المتابعين",
            editInfo: "تحرير المعلومات",
            editProfile: "تحرير الملف الشخصي",
            edit: "تحرير",
            explore: "استكشاف",
            popular: "شائع",
            follow: "متابعة",
            block: "حظر",
            blocked: "محظور",
            views: "المشاهدات",
            likes: "إعجابات",
            post: "نشر",
            liked: "معجب به",
            no: "لا أتذكر كلمة المرور",
            banner: "شعار",
            share: "مشاركة",
            options: "خيارات",
            delete: "حذف",
            report: "إبلاغ",
            page: "صفحة",
            comment: "تعليق",
            messages: "رسائل",
            save: "حفظ",
            friends: "أصدقاء",
            groups: "مجموعات",
            settings: "الإعدادات"
        },
        bn: {
            title: "স্বাগতম, এখন শুরু করুন",
            description: "আপনার অ্যাকাউন্ট তৈরি করুন এবং কিছু মিস করবেন না",
            content: "আপনার ব্যবহারকারীর নাম এবং পাসওয়ার্ড মনে রাখুন যাতে আপনি আপনার অ্যাকাউন্টে প্রবেশ করতে পারেন।",
            register: "নিবন্ধন",
            login: "প্রবেশ করুন",
            alreadyHaveAccount: "আপনার কি অ্যাকাউন্ট আছে?",
            search: "অনুসন্ধান",
            username: "ব্যবহারকারীর নাম",
            name: "নাম",
            password: "পাসওয়ার্ড",
            aboutYou: "আপনার সম্পর্কে",
            link: "লিংক",
            home: "হোম",
            notifications: "বিজ্ঞপ্তি",
            upload: "আপলোড",
            profile: "প্রোফাইল",
            logout: "লগ আউট",
            stats: "পরিসংখ্যান",
            feed: "ফিড",
            video: "ভিডিও",
            image: "ছবি",
            posts: "পোস্টগুলি",
            following: "অনুসরণ",
            followers: "অনুসারীরা",
            editInfo: "তথ্য সম্পাদনা করুন",
            editProfile: "প্রোফাইল সম্পাদনা করুন",
            edit: "সম্পাদনা",
            explore: "অন্বেষণ",
            popular: "জনপ্রিয়",
            follow: "অনুসরণ করুন",
            block: "ব্লক করুন",
            blocked: "ব্লক করা হয়েছে",
            views: "দেখেছে",
            likes: "পছন্দ",
            post: "পোস্ট করুন",
            liked: "পছন্দ হয়েছে",
            no: "পাসওয়ার্ড মনে নেই",
            banner: "ব্যানার",
            share: "শেয়ার",
            options: "অপশন",
            delete: "মুছুন",
            report: "রিপোর্ট",
            page: "পৃষ্ঠা",
            comment: "মন্তব্য করুন",
            messages: "বার্তা",
            save: "সংরক্ষণ করুন",
            friends: "বন্ধুরা",
            groups: "গ্রুপ",
            settings: "সেটিংস"
        },
        pl: {
            title: "Witamy, zacznij teraz",
            description: "Utwórz konto i nie przegap niczego",
            content: "Zapamiętaj swoją nazwę użytkownika i hasło, aby uzyskać dostęp do swojego konta.",
            register: "Zarejestruj się",
            login: "Zaloguj się",
            alreadyHaveAccount: "Masz już konto?",
            search: "Szukaj",
            username: "Nazwa użytkownika",
            name: "Imię",
            password: "Hasło",
            aboutYou: "O tobie",
            link: "Link",
            home: "Strona główna",
            notifications: "Powiadomienia",
            upload: "Prześlij",
            profile: "Profil",
            logout: "Wyloguj się",
            stats: "Statystyki",
            feed: "Kanał",
            video: "Wideo",
            image: "Obraz",
            posts: "Posty",
            following: "Obserwowane",
            followers: "Obserwujący",
            editInfo: "Edytuj informacje",
            editProfile: "Edytuj profil",
            edit: "Edytuj",
            explore: "Odkrywaj",
            popular: "Popularne",
            follow: "Obserwuj",
            block: "Zablokuj",
            blocked: "Zablokowany",
            views: "Wyświetlenia",
            likes: "Polubienia",
            post: "Opublikuj",
            liked: "Polubiono",
            no: "Nie pamiętam hasła",
            banner: "Baner",
            share: "Udostępnij",
            options: "Opcje",
            delete: "Usuń",
            report: "Zgłoś",
            page: "Strona",
            comment: "Komentarz",
            messages: "Wiadomości",
            save: "Zapisz",
            friends: "Znajomi",
            groups: "Grupy",
            settings: "Ustawienia"
        },
        it: {
            title: "Benvenuto, inizia ora",
            description: "Crea il tuo account e non perdere nulla",
            content: "Ricorda il tuo nome utente e la password per accedere al tuo account.",
            register: "Registrati",
            login: "Accedi",
            alreadyHaveAccount: "Hai già un account?",
            search: "Cerca",
            username: "Nome utente",
            name: "Nome",
            password: "Password",
            aboutYou: "Su di te",
            link: "Link",
            home: "Home",
            notifications: "Notifiche",
            upload: "Carica",
            profile: "Profilo",
            logout: "Esci",
            stats: "Statistiche",
            feed: "Feed",
            video: "Video",
            image: "Immagine",
            posts: "Post",
            following: "Seguiti",
            followers: "Follower",
            editInfo: "Modifica informazioni",
            editProfile: "Modifica profilo",
            edit: "Modifica",
            explore: "Esplora",
            popular: "Popolare",
            follow: "Segui",
            block: "Blocca",
            blocked: "Bloccato",
            views: "Visualizzazioni",
            likes: "Mi piace",
            post: "Pubblica",
            liked: "Piaciuto",
            no: "Password dimenticata",
            banner: "Banner",
            share: "Condividi",
            options: "Opzioni",
            delete: "Elimina",
            report: "Segnala",
            page: "Pagina",
            comment: "Commenta",
            messages: "Messaggi",
            save: "Salva",
            friends: "Amici",
            groups: "Gruppi",
            settings: "Impostazioni"
        },
        ko: {
            title: "환영합니다, 지금 시작하세요",
            description: "계정을 만들고 모든 것을 놓치지 마세요",
            content: "계정에 접근하려면 사용자 이름과 비밀번호를 기억하세요.",
            register: "회원가입",
            login: "로그인",
            alreadyHaveAccount: "계정이 이미 있나요?",
            search: "검색",
            username: "사용자 이름",
            name: "이름",
            password: "비밀번호",
            aboutYou: "당신에 대해",
            link: "링크",
            home: "홈",
            notifications: "알림",
            upload: "업로드",
            profile: "프로필",
            logout: "로그아웃",
            stats: "통계",
            feed: "피드",
            video: "비디오",
            image: "이미지",
            posts: "게시물",
            following: "팔로잉",
            followers: "팔로워",
            editInfo: "정보 수정",
            editProfile: "프로필 수정",
            edit: "수정",
            explore: "탐색",
            popular: "인기",
            follow: "팔로우",
            block: "차단",
            blocked: "차단됨",
            views: "조회수",
            likes: "좋아요",
            post: "게시",
            liked: "좋아요",
            no: "비밀번호를 잊어버렸어요",
            banner: "배너",
            share: "공유",
            options: "옵션",
            delete: "삭제",
            report: "신고",
            page: "페이지",
            comment: "댓글",
            messages: "메시지",
            save: "저장",
            friends: "친구",
            groups: "그룹",
            settings: "설정"
        }
    
    };

    
    function getBrowserLanguage() {
        const language = navigator.language || navigator.languages[0];
        const languageCode = language.split('-')[0]; // Obtener el código del idioma (por ejemplo, 'en' de 'en-US')
        return languageCode;
    }

    function updateLanguage(language) {
        const elements = document.querySelectorAll('[data-key]');
        elements.forEach(element => {
            const key = element.getAttribute('data-key');
            element.textContent = texts[language][key];
        });
        document.documentElement.setAttribute('lang', language); // Cambia el atributo lang del documento
    }

    function setLanguageInURL(language) {
        const urlParams = new URLSearchParams(window.location.search);
        urlParams.set('lang', language);
        history.replaceState(null, '', '?' + urlParams.toString());
    }

    const urlParams = new URLSearchParams(window.location.search);
    const langParam = urlParams.get('lang');
    const selectedLanguage = langParam || getBrowserLanguage();

    updateLanguage(selectedLanguage);
    setLanguageInURL(selectedLanguage);

    const languageSelector = document.getElementById('languageSelector');
    languageSelector.value = selectedLanguage;
    
    languageSelector.addEventListener('change', (event) => {
        const newLanguage = event.target.value;
        updateLanguage(newLanguage);
        setLanguageInURL(newLanguage);
    });
});
